### ISSUE TITLE
Error linking: "undefined reference to __exp{2}_finite"

### ISSUE THREAD

**Issue by telans** [ungoogled-software/ungoogled-chromium-archlinux#57] opened 2020-02-14 04:38 UTC
Using the AUR package `ungoogled-chromium`. If I'm not mistaken this is the repository for that, so I thought i'd better make an issue here instead.

```
[22797/22797] LINK ./chrome
FAILED: chrome 
clang++ -Wl,--version-script=../../build/linux/chrome.map -fPIC -Wl,-z,noexecstack -Wl,-z,relro -Wl,-z,now -Wl,-z,defs -Wl,--as-needed -fuse-ld=lld -Wl,--icf=all -Wl,--color-diagnostics -m64 -Wl,-O2 -Wl,--gc-sections -rdynamic -pie -Wl,--disable-new-dtags -Wl,-O2,--sort-common,--as-needed,-z,relro,-z,now -o "./chrome" -Wl,--start-group @"./chrome.rsp"  -Wl,--end-group  -latomic -ldl -lpthread -lrt -lX11 -lX11-xcb -lxcb -lXcomposite -lXcursor -lXdamage -lXext -lXfixes -lXi -lXrender -lXtst -lgmodule-2.0 -lglib-2.0 -lgobject-2.0 -lgthread-2.0 -ljsoncpp -licui18n -licuuc -licudata -lsmime3 -lnss3 -lnssutil3 -lplds4 -lplc4 -lnspr4 -lcups -lxml2 -lfontconfig -ldbus-1 -levent -lresolv -lgio-2.0 -lz -lwebpdemux -lwebpmux -lwebp -lfreetype -ljpeg -lexpat -lharfbuzz-subset -lharfbuzz -ldrm -lre2 -lXrandr -lpci -lXss -lasound -lpulse -lavcodec -lavformat -lavutil -lsnappy -lopus -latk-1.0 -latk-bridge-2.0 -lva -lpangocairo-1.0 -lpango-1.0 -lcairo -latspi -lFLAC -lminizip -lgtk-3 -lgdk-3 -lcairo-gobject -lgdk_pixbuf-2.0 -lxslt -llzma -lm -llcms2 -lopenjp2
ld.lld: error: /sbin/../lib64/gcc/x86_64-pc-linux-gnu/9.2.1/../../../../lib64/libopenjp2.so: undefined reference to __exp_finite
ld.lld: error: /sbin/../lib64/gcc/x86_64-pc-linux-gnu/9.2.1/../../../../lib64/libopenjp2.so: undefined reference to __exp2_finite
clang-9: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.
==> ERROR: A failure occurred in build().
    Aborting...
Error making: ungoogled-chromium
```

**Comment by telans** [comment] 2020-02-16 05:37
Still occouring with cdad0787f5749fed81e2afd4a48b7f0def86960d (80.0.3987.87-2)

**Comment by wchen342** [comment] 2020-02-16 22:57
@jstkdng Same problem as you mentioned before?

**Comment by jstkdng** [comment] 2020-02-17 02:18
@wchen342 
yeah, removing the `use_openjpeg2` flag fixes the problem

**Comment by wchen342** [comment] 2020-02-28 07:51
I recall something that may help finding the cause of this problem. So when #59 was opened Actions ran a build on it and [the build succeeded](https://github.com/ungoogled-software/ungoogled-chromium-archlinux/actions/runs/40196985) without a problem. However on other machines the build failed. It turns out that there is [a bug in the workflow file](https://github.com/ungoogled-software/ungoogled-chromium-archlinux/pull/62#issuecomment-591844463) and Actions is building with an unmerged version of this repo (i.e. without the pull request), which I think means some change between `79.0.3945.130` and `80.0.3987.106` in either this repo or the main `ungoogled-chromium` repo caused this error.

@braewoods @tangalbert919  Do you have any idea whether some changes during that period can cause this?

BTW this error still occurs with `80.0.3987.122`.

**Comment by braewoods** [comment] 2020-02-28 15:41
Those are symbols that are provided by libm from glibc. It could be as simple as a problem with the ordering of the linked libraries. I would try manually linking it with a changed order and see if it helps. If it does then maybe a patch for the linking order could help.

**Comment by nathanielcwm** [comment] 2020-03-01 12:12
I'm running into the same issue.

**Comment by braewoods** [comment] 2020-05-02 14:31
I've found something interesting. I tried manually linking them and discovered that it links successfully if we use GNU ld but produces this error if we use Clang's ld.lld. Thoughts on what we might make from this discovery?

**Comment by wchen342** [comment] 2020-05-02 15:21
That's interesting discovery. My knowledge in C++ is very limited but I think either it's a difference between the implementation of ld/lld, or very unlikely, a bug.
Another possibility is the Clang version. Maybe try using Clang-9?

**Comment by braewoods** [comment] 2020-05-02 15:50
Not sure where I would get clang 9 on Arch. It has clang 10 now.

**Comment by braewoods** [comment] 2020-05-02 15:59
I'll see what disabling lld in the build flags does. I only thought to try this because I used to run into weird issues that seemed to be an issue with the linker itself during my packaging days. I can't find anything to explain this odd behavior but the fact that GNU ld seems to work whereas lld does not makes me think it's not an issue with the system libraries themselves.

**Comment by wchen342** [comment] 2020-05-02 16:06
I searched on AUR but there are [clang-9](https://aur.archlinux.org/packages/clang90/) and [llvm-9](https://aur.archlinux.org/packages/llvm90/) but no lld-9.
There are [clang-7](https://aur.archlinux.org/packages/clang70/), [llvm-7](https://aur.archlinux.org/packages/llvm7/) and [lld-7](https://aur.archlinux.org/packages/lld7/) though.

Actually what clang version is Ubuntu/Debian on? The default clang is pulled from source so maybe it is not too new but too old?

I agree this is more like a problem with lonker itself, but I don't think disabling lld will be a good idea in long run since it is the only linker that is supported upstream.

**Comment by braewoods** [comment] 2020-05-02 16:10
Probably so. I only considered it a short term solution. As for Debian the Sid and Focal branches have been using clang 10 for over a month and have not been having linking errors with lld. They even have `use_system_libopenjpeg2=true` in their build flags.

**Comment by wchen342** [comment] 2020-05-02 16:19
Now that sounds like a problem with the patches. I am searching through the debian repository and find some modifications that are not here, like the usage of `-no-static-libstdc++`. Will that matter?

**Comment by braewoods** [comment] 2020-05-02 16:23
No idea. Only one way to find out. I also thought `concurrent_links=1` might play a part. I have known builds to sometimes have issues with concurrency.

**Comment by braewoods** [comment] 2020-05-02 21:44
Ok. I did a difference between the build flags and found these are present in Debian but not Arch:

`concurrent_links=1
use_goma=false
use_allocator="tcmalloc"
use_ozone=false
use_unofficial_version_number=false
enable_vr=false
optimize_webui=false
v8_enable_backtrace=true
host_cpu=x64
`

**Comment by braewoods** [comment] 2020-05-02 21:46
@wchen342 I saw you close an issue earlier. Do you have authority to merge PRs here?

**Comment by braewoods** [comment] 2020-05-02 22:46
Ok. I'll try building with clang9 once I get it built. So far our only solutions are to switch linkers or disable the failing library. Any other ideas?

**Comment by wchen342** [comment] 2020-05-02 23:00
I can merge PRs here yes. I am holding #72 for one more day and if you still can pinpoint the exact cause then I will merge it.

The flags other than `concurrent_links=1 v8_enable_backtrace=true use_ozone=false` should be unrelated.

**Comment by braewoods** [comment] 2020-05-02 23:03
Just go ahead. I don't think I'm going to find anything. It could just as easily be a difference in how Arch builds clang and llvm from Debian.

**Comment by jstkdng** [comment] 2020-05-02 23:10
Why don't you guys look at how Arch's chromium handles the problem? They don't use the flag `use_system_openjpeg2`. Maybe since the beginning or just removed when it caused this problem.

**Comment by braewoods** [comment] 2020-05-02 23:19
Yet Debian is able to build with it just fine. That's the mystery we have right now.

**Comment by wchen342** [comment] 2020-05-02 23:22
I actually don't know why some of the `use_system` flags are there in the first place. They are there since I have first come here. @Eloston probably knows.

And yes if Debian builds fine with the same flag then there is definitely a problem with Arch and it's better to find it out then just cover it up.

**Comment by braewoods** [comment] 2020-05-02 23:35
@wchen342 Could you merge my PR? I just finished rebaseing it with master. This issue is technically solved now so should we move what we've learned to a new one so we can revisit this flag later? It might get fixed with the next clang release or so.

**Comment by jstkdng** [comment] 2020-05-02 23:54
@wchen342 
The PKGBUILD was based on some version of inox, but I think nobody thought about refactoring it. Actually, Arch used to do the same, but then started using the flags array in their PKGBUILD.

@braewoods 
That may be so, that doesn't mean it has to be solved. If both ways will take to the same destination, choose the one that takes the least amount of effort.

**Comment by wchen342** [comment] 2020-05-03 00:20
@jstkdng I see. My guess of including these flags is because 1) to decrease package size 2) prevent upstream from providing malicious libs, which I think is reasonable to have.

@braewoods I have merged the PR. Feel free to open a new issue.

**Comment by wchen342** [comment] 2020-05-03 02:15
Moving discussion to #73.

**Closed** 2020-05-03 02:15 UTC
