### ISSUE TITLE
Current AUR package fails to build

### ISSUE THREAD

**Issue by flawedworld** [ungoogled-software/ungoogled-chromium-archlinux#20] opened 2019-06-20 22:43 UTC
See: https://aur.archlinux.org/packages/ungoogled-chromium#comment-697770

**Comment by dimyme** [comment] 2019-06-21 12:59
see https://aur.archlinux.org/packages/ungoogled-chromium#comment-697850

**Comment by wchen342** [comment] 2019-06-22 00:47
These are two different issues. @flawedworld Can you try this patch: [https://github.com/ungoogled-software/ungoogled-chromium-archlinux/pull/19](https://github.com/ungoogled-software/ungoogled-chromium-archlinux/pull/19)?

@dimyme Your problem is caused by not having enough physical memory. Limiting number of threads is the correct solution.
Probably in the future [autoninja](https://chromium.googlesource.com/chromium/tools/depot_tools/+/master/autoninja.py) should be used instead plain ninja, but I think this need to be discussed with the package maintianer.

**Comment by Eloston** [comment] 2019-06-22 04:18
@dimyme @wchen342 I think the better solution is to set `jumbo_file_merge_limit` as suggested here: https://github.com/ungoogled-software/ungoogled-chromium-archlinux/issues/14#issuecomment-498521254. I believe you'll get better performance by using all threads, even if the number of targets increase (due to the merge limit).

**Comment by dimyme** [comment] 2019-06-22 09:08
Anyhow, RAM usage peaks one time at ca. 8 GB while being ~ 4 GB most of the build time. Even with an eventual build, Skype.com voice calls won't work in UNGOOG-CHR. just SMS.

**Comment by wchen342** [comment] 2019-06-22 19:37
@dimyme It depends on how many cores you have on your machine. If not specified, `ninja` defaults to `num_cores + 2` threads so if someone has a machine with 20 cores but say 4GB memories then it is almost certain that it will run out of memories.
I don't know about skype, maybe have something to do with WebRTC? It's better to open a separate issue in main repo for that.
@Eloston I think you are right. I read the `autoninja` script and its logic is quite rigid anyway. The question is now we have a tunable parameter which means there is no one-fit-all solutions. Of course we can prioritize usablity so it will build on most machines with the (acceptable) shortcome of build slower even on machines which has enough memories.

**Comment by lunainvictum** [comment] 2019-06-23 13:32
i cant build it too. 
`[16521/20652] CXX obj/chrome/browser/ui/ui/ui_jumbo_70.o
ninja: build stopped: subcommand failed.
==> FEHLER: Ein Fehler geschah in build().
    Breche ab...
`
I tried https://github.com/ungoogled-software/ungoogled-chromium-archlinux/issues/14#issuecomment-504416881 and https://github.com/ungoogled-software/ungoogled-chromium-archlinux/issues/14#issuecomment-498521254 seperatly and together.

It abort everytime at Position between 16000-17000. And everytime at files that have "jumbo" in there names.

Last Week i could build https://aur.archlinux.org/packages/ungoogled-chromium-archlinux/ with no problem with JstKddng "patch" to build 75.0.3770.80-1. 

I have a Threadripper 1950x with 64gb RAM. So that cant be a issue.

**Comment by wchen342** [comment] 2019-06-23 20:38
> i cant build it too.
> `[16521/20652] CXX obj/chrome/browser/ui/ui/ui_jumbo_70.o ninja: build stopped: subcommand failed. ==> FEHLER: Ein Fehler geschah in build(). Breche ab... `

@lunainvictum Is [this](https://aur.archlinux.org/packages/ungoogled-chromium/#comment-697905) your comment? If so then please try [https://github.com/ungoogled-software/ungoogled-chromium-archlinux/pull/19](https://github.com/ungoogled-software/ungoogled-chromium-archlinux/pull/19). 
@seppiofish can you please update AUR package when possible?

> EDIT:
> Wich is the better AUR pakage?
> https://aur.archlinux.org/packages/ungoogled-chromium-archlinux/
> or
> https://aur.archlinux.org/packages/ungoogled-chromium/
> Last week i used ungoogled-chromium-archlinux because ungoogled-chromium was out-of-date.

See [https://github.com/ungoogled-software/ungoogled-chromium-archlinux/issues/18#issuecomment-503353147](https://github.com/ungoogled-software/ungoogled-chromium-archlinux/issues/18#issuecomment-503353147)
 
> And in ungoogled-chromium is a strange file named "chromium-harfbuzz-2.0.patch".

That patch used to be there to deal with Arch's harfbuzz version being too new. I don't know whether it is still necessary now.

**Comment by Eel52** [comment] 2019-06-24 02:47
I am also failing to build the package on my end. I have tried building it on an i5-2520M as well as a Ryzen 1600. Attempting the fix found here: https://github.com/Eloston/ungoogled-chromium/issues/784 does not resolve the issue, only allows the build to continue for a little longer before makepkg stopping with code 4.

**Comment by Eloston** [comment] 2019-06-24 03:11
This issue is getting messy, with two separate issues intertwined with each other. I just pushed af242f55185ff0ff530d9be502099af0b9f6349b, which should fix OOM issues during compilation (more specficially, the object generation phase). The other issue has been fixed by @wchen342 already in #19.

If you are still having issues, please open a new issue with more specific details, such as the specific error in the console output (or attach a full build log if you don't know what is relevant).

**Closed by Eloston** 2019-06-24 03:11 UTC

**Comment by lunainvictum** [comment] 2019-06-24 06:41
> @lunainvictum Is this your comment? If so then please try #19.

No. I dont have a Account at AUR. 

> This issue is getting messy, with two separate issues intertwined with each other. I just pushed af242f5, which should fix OOM issues during compilation (more specficially, the object generation phase). The other issue has been fixed by @wchen342 already in #19.

If you are still having issues, please open a new issue with more specific details, such as the specific error in the console output (or attach a full build log if you don't know what is relevant).

**Comment by Eloston** [comment] 2019-06-25 06:41
@lunainvictum 

> Is here a way to create a PKGBUILD wich use everytime the last Version from Master? https://github.com/ungoogled-software/ungoogled-chromium-archlinux/commits/master

There is, and I think it's relatively simple, but I've never done it and it hasn't been documented. (I'll accept PRs if anyone wants to document this)

> And i still dont understand the difference between https://github.com/ungoogled-software/ungoogled-chromium-archlinux/commits/master and https://github.com/Eloston/ungoogled-chromium/commits/master
> 
> Is the first one, specially for Archlinux modified? And if yes, why?

See https://github.com/Eloston/ungoogled-chromium/blob/master/README.md#source-code, which I updated recently.
