### ISSUE TITLE
Not opening after update to 111.0.5563.64-1

### ISSUE THREAD

**Issue by PistachioGuy** [ungoogled-software/ungoogled-chromium-archlinux#221] opened 2023-03-09 20:58 UTC
I'm getting this error:

/usr/lib/chromium/chromium: error while loading shared libraries: libavcodec.so.59: cannot open shared object file: No such file or directory

**Comment by PF4Public** [comment] 2023-03-09 20:59
Duplicate of #220

**Comment by PistachioGuy** [comment] 2023-03-09 21:00
Yeah I kind of noticed that after I posted it

**Comment by networkException** [comment] 2023-03-09 21:29
Closing in favor of #220

**Closed by networkException** 2023-03-09 21:29 UTC
