### ISSUE TITLE
Make CI checks work with PRs

### ISSUE THREAD

**Issue by Eloston** [ungoogled-software/ungoogled-chromium-archlinux#34] opened 2019-09-24 21:51 UTC
Context here: https://github.com/ungoogled-software/ungoogled-chromium-archlinux/pull/32#issuecomment-534697886

We need a way to make CI checks work with PRs (without having to add `[skip ci]` to make them "pass").

---

@nikolowry To address your solutions in the linked issue:

> Focus on making at the very least a master/shared "Linux" patchset repo (related discussion Eloston/ungoogled-chromium#827). Then only ArchLinux specific patches would get checked in here and we'll have to add them directly o the source array. Killing the need to checkout this repo would solve this "chicken or egg" problem.

This separates the patches from the GN configuration and other source code setup (e.g. binary pruning, domain substitution). IMO, it doesn't make sense to separate any one of those things from each other, because they are highly dependent on the specific version of Chromium we're building and it's all specific to Arch Linux. In this proposed workflow, you'd basically need to update the patches separatey from the rest of the configuration/scripts, then reference the version of the patches (e.g. commit hash) from the PKGBUILD. Technically it can work, but it's counter-intuitive.

> If we keep it as is, we'll need to extend the devutils to be able to generate tmp PKGBUILD's for PRs that would basically automate what I did for this build https://cirrus-ci.com/build/5438960035168256

Which is what I stated I want to avoid, but it sounds like it won't be possible :(

---

Another option I thought of is to move all the logic out of the PKGBUILD and into some scripts (shell, Makefile, another PKGBUILD, Python, Rust, Go, JavaScript, C++, Brainfuck, whatever) that are downloaded with the rest of the code that's already here. Then, the PKGBUILD can just be a small file that downloads this repo at a specific commit and runs the build script; in fact, the PKGBUILD can live on its own branch (e.g. `pkgbuild`, `repo`, etc.) so we don't have to run our expensive CI checks on PKGBUILD changes.

This option kind of conflicts with the idea that PKGBUILDs should handle all the downloading and building logic, but it seems to be more practical and manageable for our workflow.

**Comment by jstkdng** [comment] 2019-09-25 00:30
If this is done, it would be impossible to use this pkgbuild in the aur I think, well, it would be possible but it would break all the aur helpers since they just run makepkg once they clone the git repo in the aur.

**Comment by nikolowry** [comment] 2019-09-25 02:02
There's actually an "easy" solve for this issue @Eloston, but I didn't mention it because I imagined it would get fairly tedious to maintain --we just add everything we need to build into the source array:
```
pkgname=ungoogled-chromium
# Commit or tag for the upstream ungoogled-chromium repo
_ungoogled_version='77.0.3865.90-1'
_chromium_version=$(curl -sL https://raw.githubusercontent.com/Eloston/ungoogled-chromium/${_ungoogled_version}/chromium_version.txt)
_ungoogled_revision=$(curl -sL https://raw.githubusercontent.com/Eloston/ungoogled-chromium/${_ungoogled_version}/revision.txt)
pkgver=${_chromium_version}
_ungoogled_archlinux_pkgrel=0
pkgrel=$((_ungoogled_revision + _ungoogled_archlinux_pkgrel))
_launcher_ver=6
pkgdesc="A lightweight approach to removing Google web service dependency"
arch=('x86_64')
url="https://github.com/ungoogled-software/ungoogled-chromium-archlinux"
license=('BSD')
depends=('gtk3' 'nss' 'alsa-lib' 'xdg-utils' 'libxss' 'libcups' 'libgcrypt'
         'ttf-font' 'systemd' 'dbus' 'libpulse' 'pciutils' 'json-glib' 'libva'
         'desktop-file-utils' 'hicolor-icon-theme' 'jsoncpp' 'openjpeg2')
makedepends=('python' 'python2' 'gperf' 'yasm' 'mesa' 'ninja' 'git'
             'clang' 'lld' 'gn' 'llvm' 'quilt')
optdepends=('pepper-flash: support for Flash content'
            'kdialog: needed for file dialogs in KDE'
            'gnome-keyring: for storing passwords in GNOME keyring'
            'kwallet: for storing passwords in KWallet'
            'libva-intel-driver: for hardware video acceleration with Intel GPUs'
            'libva-mesa-driver: for hardware video acceleration with AMD/ATI GPUs'
            'libva-vdpau-driver: for hardware video acceleration with NVIDIA GPUs')
provides=('chromium')
conflicts=('chromium')
source=(https://commondatastorage.googleapis.com/chromium-browser-official/chromium-${_chromium_version}.tar.xz
        chromium-launcher-$_launcher_ver.tar.gz::https://github.com/foutrelis/chromium-launcher/archive/v$_launcher_ver.tar.gz
        "git+https://github.com/Eloston/ungoogled-chromium#tag=${_ungoogled_version}"
        flags.archlinux.gn
        patches/series
        patches/inox-patchset/chromium-skia-harmony.patch
        patches/inox-patchset/fix-cfi-failures-with-unbundled-libxml.patch
        patches/debian_buster/disable/installer.patch
        patches/debian_buster/disable/font-tests.patch
        patches/debian_buster/disable/swiftshader.patch
        patches/debian_buster/system/jpeg.patch
        patches/debian_buster/system/nspr.patch
        patches/debian_buster/system/event.patch
        patches/debian_buster/system/openjpeg.patch
        patches/debian_buster/system/convertutf.patch
        patches/archlinux/fixes/fix-wrong-string-initialization-in-LinkedHashSet.patch
        patches/archlinux/fixes/one_euro_filter.patch
        patches/archlinux/fixes/vaapi.patch
        patches/archlinux/fixes/web_time_range.patch
        patches/archlinux/system/harfbuzz.patch
        patches/archlinux/system/icu.patch
        patches/archlinux/system/jsoncpp.patch
        patches/archlinux/system/lcms.patch
        patches/archlinux/system/zlib.patch)
sha256sums=($(curl -sL https://commondatastorage.googleapis.com/chromium-browser-official/chromium-${_chromium_version}.tar.xz.hashes | grep sha256 | cut -d ' ' -f3)
            '04917e3cd4307d8e31bfb0027a5dce6d086edb10ff8a716024fbb8bb0c7dccf1'
            'SKIP'
            'SKIP'
            'SKIP'
            'SKIP'
            'SKIP'
            'SKIP'
            'SKIP'
            'SKIP'
            'SKIP'
            'SKIP'
            'SKIP'
            'SKIP'
            'SKIP'
            'SKIP'
            'SKIP'
            'SKIP'
            'SKIP'
            'SKIP'
            'SKIP'
            'SKIP'
            'SKIP'
            'SKIP')
```

It probably wouldn't be so bad if we had something similar to the `devutils/update_patches.py`.

I'll keep lurking the "Creating & Modifying Patches" at https://bbs.archlinux.org/viewforum.php?id=4 to see if someone else has any good ideas for dealing with these types of situations -- but I've been striking out so far.

**Comment by Eloston** [comment] 2019-09-25 02:08
@jstkdng Why wouldn't it work? The existing PKGBUILD already clones a git repo at a specific commit. Just move the actual building logic out of the PKGBUILD and into a build script.

@nikolowry Yeah, that's a very tedious solution. With my proposed PKGBUILD, you'd just need one source (or two sources, if submodules can't be initialized via git commands).

**Comment by Eloston** [comment] 2019-09-25 02:10
Actually, now that I'm thinking about it, autogenerating PKGBUILDs could work. We can have a CI job that verifies an autogenerated PKGBUILD, and can also push updated PKGBUILDs to a different branch (e.g. `pkgbuild`), similar to what I setup with `ungoogled-chromium-binaries`.

**Comment by nikolowry** [comment] 2019-09-25 02:53
@Eloston it's definitely doable, and then we would just run `makepkg -p <buildscript>` (https://www.archlinux.org/pacman/makepkg.8.html).

But just to play devil's advocate, I think there are benefits to going the "easy" and "tedious" route of adding all the sources to the `PKGBUILD`:
- It' simple and explicit
- Would hopefully encourage the downstream AUR maintainers to mirror this repo and stop diverging from this repo
- It's the "Arch" way, and adhering to their "guidelines" and "best practices" is most likely the only way we could ever get this promoted to the official repos (https://wiki.archlinux.org/index.php/Arch_User_Repository#How_to_get_a_PKGBUILD_into_the_community_repository?)
- It wouldn't be that tedious if there was a `devutils` script dedicated to udating the source array and generating checksums -- it would just need to be on par with how efficient the `update_patches.py` script is

But I don't have a horse in this race -- as long as I can continue to ungoogle the latest Chromium builds I'll be a happy camper. If I can help at all just @ me whenever!

**Comment by jstkdng** [comment] 2019-09-25 03:28
@nikolowry 
actually, there is an even simpler solution, just package all patches into a .tar.gz file and add it to the sources file.
> just run makepkg -p <buildscript>

That would break aur helpers, that is what I meant.

**Comment by nikolowry** [comment] 2019-09-25 03:50
@jstkdng how do you imagine that solution being integrated into the Cirrus CI task at https://github.com/ungoogled-softforware/ungoogled-chromium-archlinux/blob/master/.cirrus.yml#L29? We want every pull request to be automatically tested prior to reviewing.

I had previously setup my own Cirrus account and ran those validations independently with a temp branch that I would never try get merged in -- I had to point the source to my fork,  https://github.com/nikolowry/ungoogled-chromium-archlinux/blob/ci/validate/PKGBUILD#L39, to be able to run the tasks without failing https://cirrus-ci.com/build/5438960035168256.

**Comment by Eloston** [comment] 2019-09-25 04:26
@nikolowry So it looks like we have consensus on automatically generating the PKGBUILD, but not on how much we should automate. For now, it's probably best to just substitute the versions (both ungoogled-chromium and ungoogled-chromium-archlinux), and generate the sources at a later time.

**Comment by nikolowry** [comment] 2019-09-25 04:44
I have a few deadlines due at the end of the week, so I'll be checking back here in a few days to see if I can't help with anything. Appreciate everyone's responsiveness!

**Comment by jstkdng** [comment] 2019-09-25 15:22
@nikolowry 
tbh I don't see a reason to setup continuous integration, just a simple "It builds!" from the original poster is enough imo.
We are only increasing the complexity of something that really doesn't require it, specially in this small project (being ungoogled-chromium-archlinux).
Of course, that is just my opinion, I like the manual way more than automating stuff.

\*cracks*
 \*sips*
yup, those were the good ol' days, before automation

**Comment by nikolowry** [comment] 2019-09-25 22:33
@jstkding some context, a few weeks ago a pull request was accepted and it passed the only CI task at that time which was `validate_with_source`. Seeing a new version was ready, I immediately pulled and was excited to build when `makepkg` suddenly threw an error. You can see the hotfix that was pushed to deal with it here https://github.com/ungoogled-software/ungoogled-chromium-archlinux/pull/27

"Scouts honor" doesn't prevent broken code from making it's way in. Once a workflow is in place, it should lead to less complexity because the task will at least guarantee everyone can successfully run `prepare` in the `PKGBUILD`

**Comment by jstkdng** [comment] 2019-09-25 23:15
@nikolowry 
ah yes, #15, the last thing you'd want in your github repository is someone's uneeded complexity. But as it turns out, that might be what you get.
Now, jokes aside.
You could achieve what you want by just adding all the patches to the sources array, just how arch already does.
![image](https://user-images.githubusercontent.com/52050345/65646108-871bbb80-dfbf-11e9-9da7-28b9b77d6d87.png)
Just remove the debian-buster patches, I don't think they are required anyway. With each PR the sources array could be modified accordingly and we wouldn't be trying to get an unexistent commit.
Also, I'd say it would be nice having someone who actually uses arch to be have permissions in this repo. Afaik @Eloston uses debian.

**Comment by Eloston** [comment] 2019-09-27 08:00
> Also, I'd say it would be nice having someone who actually uses arch to be have permissions in this repo.

I've been trying to do this for a while now, but it's not an easy problem to solve. If there's enough interest in this, I can make an issue to discuss it.

**Comment by wchen342** [comment] 2019-09-27 16:17
If I understand correctly, the problem is a PR is not actually in the repo yet so PKGBUILD cannot checkout it?
I had a look at the CI files, and I see it has access to the PR files locally. So why not just edit the PKGBUILD file in the CI env and change the line `"git+https://github.com/ungoogled-software/ungoogled-chromium-archlinux.git#commit=${_ungoogled_archlinux_version}"` to point to the local repo? 
IMO listing all files in PKGBUILD is a bad idea, especially if one day we need to put more than patches there.

BTW I use Arch daily but I think it shouldn't be too hard to just fire up a VM?

**Comment by jstkdng** [comment] 2019-09-27 17:32
>BTW I use Arch daily but I think it shouldn't be too hard to just fire up a VM?
what?
>IMO listing all files in PKGBUILD is a bad idea, especially if one day we need to put more than patches there.
IMO we should follow what arch is already doing. (In this case adding all patches to the sources array) and of course deleting uneeded patches.

**Comment by nikolowry** [comment] 2019-09-27 23:01
@wchen32 your on the right track. 

In the Cirrus `validate_makepkg_script ` we need to get the remote of the current commit and update the source array to point to that remote instead. Since we don't need to commit the `PKGBUILD` back, we could probably just `sed -i`

**Comment by wchen342** [comment] 2019-09-28 00:53
@nikolowry Yeah that's about what I was thinking. What I have in mind is we don't actually need to pull the remote in CI testing, just use local files as the repo. We can just do something like
```
 - git init
 - sed -i -E 's@        "git\+https://github\.com/ungoogled-software/ungoogled-chromium-archlinux\.git#commit=\$\{_ungoogled_archlinux_version\}"@        "git\+file://\."@g' PKGBUILD
```

in the `validate_makepkg_script` section.

@jstkdng I thought you wanted someone who uses Arch to test the repo?

**Comment by nikolowry** [comment] 2019-09-28 00:57
At the moment I don't have time to start a PR and validate any code changes, but I wanted to document what I'm thinking might be the minimal changes to `.cirrus.yml` to pull this off:
```yaml
validate_makepkg_task:
    skip: "!changesInclude('PKGBUILD', 'patches/**/*')"
    env:
        UNGOOGLED_ARCHLINUX_REPO_URL: https://github.com/ungoogled-software/ungoogled-chromium-archlinux.git
    validate_makepkg_script:
        - chmod -R 777 .
        - pacman -Sy
        - sed -i -E "s|(_ungoogled_archlinux_version=).+|\1$(git rev-parse HEAD)|" PKGBUILD
        - sed -i -E "s|(git\+)$UNGOOGLED_ARCHLINUX_REPO_URL|\1$CIRRUS_REPO_CLONE_URL|" PKGBUILD
        - sudo -u nobody makepkg --cleanbuild --syncdeps --nobuild --noconfirm
```

Also added a conditional to only run the `validate_makepkg_task` when either `PKGBUILD` or `patches/**/*` has changed -- the rationale being those file changes are the only ones that are relevant to `makepkg`'s `prepare`. 

Cirrus'  documentation is located at https://cirrus-ci.org/guide/writing-tasks/

**Comment by nikolowry** [comment] 2019-09-28 00:59
@wchen342 good thinking on the `git+file://` -- that would be a little more elegant since it eliminates the need for updating the commit hash in the `PKGBUILD`

**Comment by Eloston** [comment] 2019-09-28 09:02
I attempted a solution in #35, but I won't be able to progress much further on it. Please check it out for more details.

**Comment by jstkdng** [comment] 2019-09-28 13:21
>I thought you wanted someone who uses Arch to test the repo?

yes
>BTW I use Arch daily but I think it shouldn't be too hard to just fire up a VM?

the first part says that you use arch daily but the second part implies that you don't use arch but you can fire up a vm, also, why the question mark?

**Comment by braewoods** [comment] 2020-04-30 09:29
This seems related to #70. So I was reviewing the PKGBUILD and found a few things that could use improvements, notably areas where version updates could use a helper script. If I was going to implement OBS support I would want to start by making the existing scripts easier to update automatically. I think I will work on that after my version update is accepted.

**Comment by jstkdng** [comment] 2020-05-16 15:06
#76 should fix this problem. Closing.

**Closed by jstkdng** 2020-05-16 15:06 UTC
Labels: enhancement
