### ISSUE TITLE
no support for aarch64

### ISSUE THREAD

**Issue by ClowdyAllDay** [ungoogled-software/ungoogled-chromium-archlinux#144] opened 2021-08-26 22:16 UTC
please add aarch64 support.  thankyou!

**Comment by ClowdyAllDay** [comment] 2021-08-29 10:00
so i have both repos and both pkgbuilds and i have a guidiff as i am not proficient with vi or vim and am not a coder.  So that brings me to two problems.

I have never written a pkgbuild before much less merged one, my chances of getting this right under the best of circumstances is slim.

2nd problem is i'm not under the best of circumstances as i have a 1280x720p monitor and cant see all three columns on my screen at once to even attempt merging the pkgbuilds.

I am more than happy to spend the 24 plus hours to build this merged pkgbuild on my pi4b8gb but it would be great if you could merge these pkgbuilds

https://pastebin.com/D1ruL5pP aarch64 chromium
https://pastebin.com/JYj9W0aW ungoogled-chromium

please and thank you!  <3

**Comment by ClowdyAllDay** [comment] 2021-08-29 11:45
Seems Strit directed me to here:

https://gitlab.com/ohfp/caidao/ and this is indeed that, TY!

**Comment by jstkdng** [comment] 2021-08-29 12:04
ah yes, I remember seeing that project, just couldn't remember the name. If that is what you were looking for then the issue is solved. Closing.

**Closed by jstkdng** 2021-08-29 12:04 UTC
Labels: enhancement, help wanted
