### ISSUE TITLE
ungoogled-chromium does not build on arch linux arm anymore

### ISSUE THREAD

**Issue by pnumeultramicrospocic** [ungoogled-software/ungoogled-chromium-archlinux#241] opened 2023-09-06 14:35 UTC
Ungoogled-chromium fails to build on Arch Linux, and what to do to fix this error? "[20569/55284] CXX obj/ui/base/wayland/color_manager_util/color_manager_util.o
FAILED: obj/ui/base/wayland/color_manager_util/color_manager_util.o
clang++ -MMD -MF obj/ui/base/wayland/color_manager_util/color_manager_util.o.d -DUSE_UDEV -DUSE_AURA=1 -DUSE_GLIB=1 -DUSE_OZONE=1 -DOFFICIAL_BUILD -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D_FORTIFY_SOURCE=2 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -DNO_UNWIND_TABLES -D_GNU_SOURCE -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -DGLIB_VERSION_MAX_ALLOWED=GLIB_VERSION_2_56 -DGLIB_VERSION_MIN_REQUIRED=GLIB_VERSION_2_56 -DBASE_USE_PERFETTO_CLIENT_LIBRARY=1 -DSK_ENABLE_SKSL -DSK_UNTIL_CRBUG_1187654_IS_FIXED -DSK_USER_CONFIG_HEADER="../../skia/config/SkUserConfig.h" -DSK_WIN_FONTMGR_NO_SIMULATIONS -DSK_DISABLE_LEGACY_SKSURFACE_METHODS -DSK_DISABLE_LEGACY_GRAPHITE_IMAGE_FACTORIES -DSK_DISABLE_LEGACY_GRAPHITE_IMAGE_METHODS -DSK_DISABLE_LEGACY_SKSURFACE_FACTORIES -DSK_DISABLE_LEGACY_SKSURFACE_FLUSH -DSK_DISABLE_LEGACY_SKSURFACE_AS_IMAGE -DSK_DISABLE_LEGACY_SKSURFACE_DISPLAYLIST -DSK_CODEC_DECODES_JPEG -DSK_CODEC_DECODES_PNG -DSK_CODEC_DECODES_WEBP -DSK_ENCODE_JPEG -DSK_ENCODE_PNG -DSK_ENCODE_WEBP -DSK_HAS_WUFFS_LIBRARY -DSK_GANESH -DSK_GPU_WORKAROUNDS_HEADER="gpu/config/gpu_driver_bug_workaround_autogen.h" -DSK_GL -DSK_VULKAN=1 -DSK_GRAPHITE -DVK_USE_PLATFORM_XCB_KHR -DVK_USE_PLATFORM_WAYLAND_KHR -I../.. -Igen -I../../third_party/perfetto/include -Igen/third_party/perfetto/build_config -Igen/third_party/perfetto -Igen/shim_headers/zlib_shim -Igen/shim_headers/jsoncpp_shim -Igen/shim_headers/icui18n_shim -Igen/shim_headers/icuuc_shim -Igen/shim_headers/libpng_shim -Igen/shim_headers/libwebp_shim -I../../third_party/abseil-cpp -I../../third_party/boringssl/src/include -I../../third_party/protobuf/src -Igen/protoc_out -Igen/components/exo/wayland/protocol -I../../third_party/wayland/include -I../../third_party/wayland/include/src -I../../third_party/wayland/src/cursor -I../../third_party/wayland/src/egl -I../../third_party/wayland/src/src -Igen/third_party/wayland/src/protocol -I../../third_party/skia -Igen/third_party/skia -I../../third_party/wuffs/src/release/c -I../../third_party/vulkan/include -I../../third_party/vulkan-deps/vulkan-headers/src/include -Wall -Wextra -Wimplicit-fallthrough -Wextra-semi -Wunreachable-code-aggressive -Wthread-safety -Wno-missing-field-initializers -Wno-unused-parameter -Wno-psabi -Wloop-analysis -Wno-unneeded-internal-declaration -Wenum-compare-conditional -Wno-ignored-pragma-optimize -Wno-deprecated-builtins -Wno-bitfield-constant-conversion -Wno-deprecated-this-capture -Wshadow -fno-delete-null-pointer-checks -fno-ident -fno-strict-aliasing --param=ssp-buffer-size=4 -fstack-protector -fno-unwind-tables -fno-asynchronous-unwind-tables -fPIC -pthread -fcolor-diagnostics -fmerge-all-constants -fcrash-diagnostics-dir=../../tools/clang/crashreports -mllvm -instcombine-lower-dbg-declare=0 -ffp-contract=off -flto=thin -fsplit-lto-unit -fwhole-program-vtables -mbranch-protection=standard --target=aarch64-linux-gnu -mno-outline -ffile-compilation-dir=. -no-canonical-prefixes -ftrivial-auto-var-init=pattern -O2 -fdata-sections -ffunction-sections -fno-unique-section-names -fno-omit-frame-pointer -g0 -fvisibility=hidden -Wheader-hygiene -Wstring-conversion -Wtautological-overlap-compare -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/sysprof-4 -DPROTOBUF_ALLOW_DEPRECATED=1 -Wno-redundant-parens -std=c++20 -Wno-trigraphs -gsimple-template-names -fno-exceptions -fno-rtti -fvisibility-inlines-hidden -D__DATE__= -D__TIME__= -D__TIMESTAMP__= -march=armv8.5-a -mtune=apple-m1 -O3 -pipe -fstack-protector-strong -fno-plt -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security -Wno-builtin-macro-redefined -Wno-unknown-warning-option -c ../../ui/base/wayland/color_manager_util.cc -o obj/ui/base/wayland/color_manager_util/color_manager_util.o
In file included from ../../ui/base/wayland/color_manager_util.cc:5:
../../ui/base/wayland/color_manager_util.h:55:7: error: no matching constructor for initialization of 'ui::wayland::PrimaryVersion'
PrimaryVersion(gfx::ColorSpace::PrimaryID::SMPTE170M,
^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../ui/base/wayland/color_manager_util.h:33:8: note: candidate constructor (the implicit copy constructor) not viable: requires 1 argument, but 2 were provided
struct PrimaryVersion {
^
../../ui/base/wayland/color_manager_util.h:33:8: note: candidate constructor (the implicit move constructor) not viable: requires 1 argument, but 2 were provided
../../ui/base/wayland/color_manager_util.h:33:8: note: candidate constructor (the implicit default constructor) not viable: requires 0 arguments, but 2 were provided
../../ui/base/wayland/color_manager_util.h:58:7: error: no matching constructor for initialization of 'ui::wayland::PrimaryVersion'
PrimaryVersion(gfx::ColorSpace::PrimaryID::BT470BG,
^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../ui/base/wayland/color_manager_util.h:33:8: note: candidate constructor (the implicit copy constructor) not viable: requires 1 argument, but 2 were provided
struct PrimaryVersion {
^
../../ui/base/wayland/color_manager_util.h:33:8: note: candidate constructor (the implicit move constructor) not viable: requires 1 argument, but 2 were provided
../../ui/base/wayland/color_manager_util.h:33:8: note: candidate constructor (the implicit default constructor) not viable: requires 0 arguments, but 2 were provided
../../ui/base/wayland/color_manager_util.h:61:7: error: no matching constructor for initialization of 'ui::wayland::PrimaryVersion'
PrimaryVersion(gfx::ColorSpace::PrimaryID::SMPTE170M,
^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../ui/base/wayland/color_manager_util.h:33:8: note: candidate constructor (the implicit copy constructor) not viable: requires 1 argument, but 2 were provided
struct PrimaryVersion {
^
../../ui/base/wayland/color_manager_util.h:33:8: note: candidate constructor (the implicit move constructor) not viable: requires 1 argument, but 2 were provided
../../ui/base/wayland/color_manager_util.h:33:8: note: candidate constructor (the implicit default constructor) not viable: requires 0 arguments, but 2 were provided
../../ui/base/wayland/color_manager_util.h:64:7: error: no matching constructor for initialization of 'ui::wayland::PrimaryVersion'
PrimaryVersion(gfx::ColorSpace::PrimaryID::BT709, kDefaultSinceVersion)},
^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../ui/base/wayland/color_manager_util.h:33:8: note: candidate constructor (the implicit copy constructor) not viable: requires 1 argument, but 2 were provided
struct PrimaryVersion {
^
../../ui/base/wayland/color_manager_util.h:33:8: note: candidate constructor (the implicit move constructor) not viable: requires 1 argument, but 2 were provided
../../ui/base/wayland/color_manager_util.h:33:8: note: candidate constructor (the implicit default constructor) not viable: requires 0 arguments, but 2 were provided
../../ui/base/wayland/color_manager_util.h:66:7: error: no matching constructor for initialization of 'ui::wayland::PrimaryVersion'
PrimaryVersion(gfx::ColorSpace::PrimaryID::BT2020, kDefaultSinceVersion)},
^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../ui/base/wayland/color_manager_util.h:33:8: note: candidate constructor (the implicit copy constructor) not viable: requires 1 argument, but 2 were provided
struct PrimaryVersion {
^
../../ui/base/wayland/color_manager_util.h:33:8: note: candidate constructor (the implicit move constructor) not viable: requires 1 argument, but 2 were provided
../../ui/base/wayland/color_manager_util.h:33:8: note: candidate constructor (the implicit default constructor) not viable: requires 0 arguments, but 2 were provided
../../ui/base/wayland/color_manager_util.h:68:7: error: no matching constructor for initialization of 'ui::wayland::PrimaryVersion'
PrimaryVersion(gfx::ColorSpace::PrimaryID::BT709, kDefaultSinceVersion)},
^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../ui/base/wayland/color_manager_util.h:33:8: note: candidate constructor (the implicit copy constructor) not viable: requires 1 argument, but 2 were provided
struct PrimaryVersion {
^
../../ui/base/wayland/color_manager_util.h:33:8: note: candidate constructor (the implicit move constructor) not viable: requires 1 argument, but 2 were provided
../../ui/base/wayland/color_manager_util.h:33:8: note: candidate constructor (the implicit default constructor) not viable: requires 0 arguments, but 2 were provided
../../ui/base/wayland/color_manager_util.h:70:7: error: no matching constructor for initialization of 'ui::wayland::PrimaryVersion'
PrimaryVersion(gfx::ColorSpace::PrimaryID::P3, kDefaultSinceVersion)},
^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../ui/base/wayland/color_manager_util.h:33:8: note: candidate constructor (the implicit copy constructor) not viable: requires 1 argument, but 2 were provided
struct PrimaryVersion {
^
../../ui/base/wayland/color_manager_util.h:33:8: note: candidate constructor (the implicit move constructor) not viable: requires 1 argument, but 2 were provided
../../ui/base/wayland/color_manager_util.h:33:8: note: candidate constructor (the implicit default constructor) not viable: requires 0 arguments, but 2 were provided
../../ui/base/wayland/color_manager_util.h:72:7: error: no matching constructor for initialization of 'ui::wayland::PrimaryVersion'
PrimaryVersion(gfx::ColorSpace::PrimaryID::ADOBE_RGB,
^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../ui/base/wayland/color_manager_util.h:33:8: note: candidate constructor (the implicit copy constructor) not viable: requires 1 argument, but 2 were provided
struct PrimaryVersion {
^
../../ui/base/wayland/color_manager_util.h:33:8: note: candidate constructor (the implicit move constructor) not viable: requires 1 argument, but 2 were provided
../../ui/base/wayland/color_manager_util.h:33:8: note: candidate constructor (the implicit default constructor) not viable: requires 0 arguments, but 2 were provided
../../ui/base/wayland/color_manager_util.h:75:7: error: no matching constructor for initialization of 'ui::wayland::PrimaryVersion'
PrimaryVersion(
^
../../ui/base/wayland/color_manager_util.h:33:8: note: candidate constructor (the implicit copy constructor) not viable: requires 1 argument, but 2 were provided
struct PrimaryVersion {
^
../../ui/base/wayland/color_manager_util.h:33:8: note: candidate constructor (the implicit move constructor) not viable: requires 1 argument, but 2 were provided
../../ui/base/wayland/color_manager_util.h:33:8: note: candidate constructor (the implicit default constructor) not viable: requires 0 arguments, but 2 were provided
../../ui/base/wayland/color_manager_util.h:79:7: error: no matching constructor for initialization of 'ui::wayland::PrimaryVersion'
PrimaryVersion(
^
../../ui/base/wayland/color_manager_util.h:33:8: note: candidate constructor (the implicit copy constructor) not viable: requires 1 argument, but 2 were provided
struct PrimaryVersion {
^
../../ui/base/wayland/color_manager_util.h:33:8: note: candidate constructor (the implicit move constructor) not viable: requires 1 argument, but 2 were provided
../../ui/base/wayland/color_manager_util.h:33:8: note: candidate constructor (the implicit default constructor) not viable: requires 0 arguments, but 2 were provided
../../ui/base/wayland/color_manager_util.h:83:7: error: no matching constructor for initialization of 'ui::wayland::PrimaryVersion'
PrimaryVersion(
^
../../ui/base/wayland/color_manager_util.h:33:8: note: candidate constructor (the implicit copy constructor) not viable: requires 1 argument, but 2 were provided
struct PrimaryVersion {
^
../../ui/base/wayland/color_manager_util.h:33:8: note: candidate constructor (the implicit move constructor) not viable: requires 1 argument, but 2 were provided
../../ui/base/wayland/color_manager_util.h:33:8: note: candidate constructor (the implicit default constructor) not viable: requires 0 arguments, but 2 were provided
../../ui/base/wayland/color_manager_util.h:87:7: error: no matching constructor for initialization of 'ui::wayland::PrimaryVersion'
PrimaryVersion(
^
../../ui/base/wayland/color_manager_util.h:33:8: note: candidate constructor (the implicit copy constructor) not viable: requires 1 argument, but 2 were provided
struct PrimaryVersion {
^
../../ui/base/wayland/color_manager_util.h:33:8: note: candidate constructor (the implicit move constructor) not viable: requires 1 argument, but 2 were provided
../../ui/base/wayland/color_manager_util.h:33:8: note: candidate constructor (the implicit default constructor) not viable: requires 0 arguments, but 2 were provided
../../ui/base/wayland/color_manager_util.h:91:7: error: no matching constructor for initialization of 'ui::wayland::PrimaryVersion'
PrimaryVersion(
^
../../ui/base/wayland/color_manager_util.h:33:8: note: candidate constructor (the implicit copy constructor) not viable: requires 1 argument, but 2 were provided
struct PrimaryVersion {
^
../../ui/base/wayland/color_manager_util.h:33:8: note: candidate constructor (the implicit move constructor) not viable: requires 1 argument, but 2 were provided
../../ui/base/wayland/color_manager_util.h:33:8: note: candidate constructor (the implicit default constructor) not viable: requires 0 arguments, but 2 were provided
../../ui/base/wayland/color_manager_util.h:95:7: error: no matching constructor for initialization of 'ui::wayland::PrimaryVersion'
PrimaryVersion(
^
../../ui/base/wayland/color_manager_util.h:33:8: note: candidate constructor (the implicit copy constructor) not viable: requires 1 argument, but 2 were provided
struct PrimaryVersion {
^
../../ui/base/wayland/color_manager_util.h:33:8: note: candidate constructor (the implicit move constructor) not viable: requires 1 argument, but 2 were provided
../../ui/base/wayland/color_manager_util.h:33:8: note: candidate constructor (the implicit default constructor) not viable: requires 0 arguments, but 2 were provided
../../ui/base/wayland/color_manager_util.h:99:7: error: no matching constructor for initialization of 'ui::wayland::PrimaryVersion'
PrimaryVersion(
^
../../ui/base/wayland/color_manager_util.h:33:8: note: candidate constructor (the implicit copy constructor) not viable: requires 1 argument, but 2 were provided
struct PrimaryVersion {
^
../../ui/base/wayland/color_manager_util.h:33:8: note: candidate constructor (the implicit move constructor) not viable: requires 1 argument, but 2 were provided
../../ui/base/wayland/color_manager_util.h:33:8: note: candidate constructor (the implicit default constructor) not viable: requires 0 arguments, but 2 were provided
../../ui/base/wayland/color_manager_util.h:110:6: error: no matching constructor for initialization of 'ui::wayland::TransferVersion'
TransferVersion(gfx::ColorSpace::TransferID::LINEAR,
^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../ui/base/wayland/color_manager_util.h:28:8: note: candidate constructor (the implicit copy constructor) not viable: requires 1 argument, but 2 were provided
struct TransferVersion {
^
../../ui/base/wayland/color_manager_util.h:28:8: note: candidate constructor (the implicit move constructor) not viable: requires 1 argument, but 2 were provided
../../ui/base/wayland/color_manager_util.h:28:8: note: candidate constructor (the implicit default constructor) not viable: requires 0 arguments, but 2 were provided
../../ui/base/wayland/color_manager_util.h:113:6: error: no matching constructor for initialization of 'ui::wayland::TransferVersion'
TransferVersion(gfx::ColorSpace::TransferID::SRGB, kDefaultSinceVersion)},
^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../ui/base/wayland/color_manager_util.h:28:8: note: candidate constructor (the implicit copy constructor) not viable: requires 1 argument, but 2 were provided
struct TransferVersion {
^
../../ui/base/wayland/color_manager_util.h:28:8: note: candidate constructor (the implicit move constructor) not viable: requires 1 argument, but 2 were provided
../../ui/base/wayland/color_manager_util.h:28:8: note: candidate constructor (the implicit default constructor) not viable: requires 0 arguments, but 2 were provided
../../ui/base/wayland/color_manager_util.h:115:6: error: no matching constructor for initialization of 'ui::wayland::TransferVersion'
TransferVersion(gfx::ColorSpace::TransferID::BT709,
^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../ui/base/wayland/color_manager_util.h:28:8: note: candidate constructor (the implicit copy constructor) not viable: requires 1 argument, but 2 were provided
struct TransferVersion {
^
../../ui/base/wayland/color_manager_util.h:28:8: note: candidate constructor (the implicit move constructor) not viable: requires 1 argument, but 2 were provided
../../ui/base/wayland/color_manager_util.h:28:8: note: candidate constructor (the implicit default constructor) not viable: requires 0 arguments, but 2 were provided
../../ui/base/wayland/color_manager_util.h:118:6: error: no matching constructor for initialization of 'ui::wayland::TransferVersion'
TransferVersion(gfx::ColorSpace::TransferID::GAMMA24,
^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../ui/base/wayland/color_manager_util.h:28:8: note: candidate constructor (the implicit copy constructor) not viable: requires 1 argument, but 2 were provided
struct TransferVersion {
^
../../ui/base/wayland/color_manager_util.h:28:8: note: candidate constructor (the implicit move constructor) not viable: requires 1 argument, but 2 were provided
../../ui/base/wayland/color_manager_util.h:28:8: note: candidate constructor (the implicit default constructor) not viable: requires 0 arguments, but 2 were provided
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
[20578/55284] ACTION //third_party/dev...uild/toolchain/linux/unbundle:default)' what to do? @PF4Public

**Comment by PF4Public** [comment] 2023-09-06 15:40
Duplicate of https://github.com/ungoogled-software/ungoogled-chromium-archlinux/issues/240

**Closed** 2023-09-06 15:40 UTC
